### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by trollbreeder** [Kleberstoff/DECryptSuite#1]
How do i use this tool?

**Comment by Kleberstoff** [comment]
Sorry for the late respond, It's CLI (Command Line Interface) - It works via the Windows CMD, Open the CMD in the same folder as the Assembly, (Shift + Rightclick, is a good shortcut) and then call it with it's name and arguments.

DECryptSuite.exe -h | For help

Note for myself, Add Example for usage.
Note for others: GUI is being Made, and it has been pushed to the #gui branch, Check that out, It's not finished yet but will be hopefully very soon! I'll include a somewhat done Beta. Use at your own Risk 👌 

https://upload.kleberstoff.xyz/uZa9Vswe.zip (Can't add .zip in Issues.)
